# Generated by Django 6.0.1 on 2026-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(blank=True, help_text='Google AdSense publisher ID (ca-pub-xxxxxxxxxxxxxxxx)', max_length=255)),
                ('adsense_enabled', models.BooleanField(default=False, help_text='Enable AdSense ads on site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
