# Generated by Django 6.0.1 on 2026-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(blank=True, help_text='AdSense Publisher ID (ca-pub-xxxxxxxxxxxxxxxx)', max_length=50, null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Enable AdSense ads across the site')),
                ('homepage_ad_unit_id', models.CharField(blank=True, help_text='Ad unit ID for homepage', max_length=50, null=True)),
                ('post_sidebar_ad_unit_id', models.CharField(blank=True, help_text='Ad unit ID for post detail sidebar', max_length=50, null=True)),
                ('post_content_ad_unit_id', models.CharField(blank=True, help_text='Ad unit ID for inside post content', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AdSense Settings',
                'verbose_name_plural': 'AdSense Settings',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
